baseURL: 'https://ibm-apiconnect.github.io/saas-welcome-pack/'
languageCode: 'en-us'
title: 'API Connect'
preserveTaxonomyNames: 'true'
theme: 'carbon-hugo-theme'
pluralizelisttitles:  "false"
sectionPagesMenu: "main"
params:
  org: 'IBM'
  profilePic: 'apic-hero-image.svg'
  subtitle: ''
  sidemenu: 'main'
  sidenav: false
  customCss: 'welcome-kit.css'
  instanaKey: '72t6dm9VQ_KDAa7pNyn6dA'
menu:
  header:
   - url: "/getting-started/"
     name: "Getting Started"
     weight: 3
   - url: "/events/"
     name: "Upcoming Events"
     weight: 4

outputs:
  section: ["html","json"]
  term: ["html","json"]